version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: feedbackcraft-postgres
    environment:
      POSTGRES_DB: feedbackcraftdb
      POSTGRES_USER: saima
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: feedbackcraft-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: saimay12343@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - my-network


volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge